# Generated by Django 5.1.3 on 2024-12-02 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='почта')),
                ('contry', models.CharField(max_length=32, verbose_name='страна')),
                ('city', models.CharField(max_length=64, verbose_name='город')),
                ('street', models.CharField(max_length=128, verbose_name='улица')),
                ('house', models.CharField(max_length=8, verbose_name='номер дома')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='название продукта')),
                ('model', models.CharField(max_length=64, verbose_name='название модели')),
                ('release_date', models.DateField(verbose_name='дата выхода продукта на рынок')),
            ],
        ),
        migrations.CreateModel(
            name='NetworkNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='название звена')),
                ('node_type', models.CharField(choices=[('FC', 'Завод'), ('RN', 'Розничная сеть'), ('IE', 'Индивидуальный предприниматель')], max_length=128, verbose_name='тип звена')),
                ('debt', models.PositiveIntegerField(verbose_name='задолжность')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата и время создания')),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NetworkManager.contacts', verbose_name='контакт')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NetworkManager.networknode', verbose_name='поставщик')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='NetworkManager.product', verbose_name='продукт')),
            ],
        ),
    ]
