# Generated by Django 5.1.3 on 2024-12-02 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkManager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networknode',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='NetworkManager.networknode', verbose_name='поставщик'),
        ),
    ]
