# Generated by Django 5.1.3 on 2024-12-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NetworkManager', '0002_alter_networknode_provider'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='Contact',
        ),
    ]
